[package]
name = "docueyes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
rust-bert = "0.23.0"
kd-tree = "0.6.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
